name: m3_antagonist_ml
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn=1.7.1
  - rdkit=2026.3.1
  - joblib
  - pip
  - pip:
      - umap-learn==0.5.11
